const ignisAccessories = {
  error: false,
  errors: null,
  data: {
    parentCategories: [
      {
        parentCategoryCd: 'INT',
        parentCategoryDesc: 'Interior',
        subCategories: [
          {
            l2CatgCd: 'MATS',
            l2CatgName: 'Mats',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '75901M66RA0',
                partDesc: 'PVC Designer Mat',
                catg3DId: 'hp_mat',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_ACC_MATS',
                ccPartMeshName: 'IGNIS_MMC_A_Z_D_S_IN_ACC_DESIGNER_MAT_MESH',
                ccPart3dId: 'IGNIS_MMC_A_Z_D_S_IN_ACC_DESIGNER_MAT_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-pvcdesignermat.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-pvcdesignermat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-pvcdesignermat.jpg',
                ],
              },
              {
                partNum: '75901M66R30',
                partDesc: '3D Mat',
                catg3DId: 'hp_bootmat',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_BOOTMAT',
                ccPartMeshName: 'IGNIS_MMC_A_Z_D_S_IN_ACC_3DBOOT_MAT_MESH',
                ccPart3dId: 'IGNIS_MMC_A_Z_D_S_IN_ACC_3DBOOT_MAT_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 2944.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-3dmat.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-3dmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-3dmat.jpg',
                ],
              },
            ],
          },
          {
            l2CatgCd: 'SCR',
            l2CatgName: 'Seat Covers',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M66RB3-130',
                partDesc: 'Implode Red Crossings',
                catg3DId: 'hp_in_SeatCover',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_SEATS',
                ccPartMeshName: 'IGNIS_ALPHA_IN_ACC_SEAT_IMPLODEREDCROSSINGS',
                ccPart3dId: 'IGNIS_ALPHA_IN_ACC_SEAT_IMPLODEREDCROSSINGS',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-imploderedcrossings.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-imploderedcrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-imploderedcrossings.jpg',
                ],
              },
              {
                partNum: '990J0M66RB3-110',
                partDesc: 'Implode Silver Crossings',
                catg3DId: 'hp_in_SeatCover',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_SEATS',
                ccPartMeshName: 'IGNIS_ALPHA_IN_ACC_SEAT_IMPLODESILVERCROSSINGS',
                ccPart3dId: 'IGNIS_ALPHA_IN_ACC_SEAT_IMPLODESILVERCROSSINGS',
                isPackage: null,
                packagePriorityOrder: null,
                price: 2944.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-implodesilvercrossings.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-implodesilvercrossings.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-implodesilvercrossings.jpg',
                ],
              },
            ],
          },
          {
            l2CatgCd: 'STI',
            l2CatgName: 'Styling Kit',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M66RPJ-010',
                partDesc: 'Interior Styling Kit Titanium',
                catg3DId: 'hp_in_lnterior_Styling_Kit',
                ccOverlappingCodes: null,
                ccPartTagName: 'INTERIOR_STYLINGKIT',
                ccPartMeshName: null,
                ccPart3dId: null,
                isPackage: null,
                packagePriorityOrder: null,
                price: 5790.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-interiorstylingkittitanium.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-interiorstylingkittitanium.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-interiorstylingkittitanium.jpg',
                ],
              },
              {
                partNum: '990J0M66RPJ-020',
                partDesc: 'Interior Styling Kit Red',
                catg3DId: 'hp_in_lnterior_Styling_Kit',
                ccOverlappingCodes: null,
                ccPartTagName: 'INTERIOR_STYLINGKIT',
                ccPartMeshName: null,
                ccPart3dId: null,
                isPackage: null,
                packagePriorityOrder: null,
                price: 5690.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-interiorstylingkitred.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-interiorstylingkitred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-interiorstylingkitred.jpg',
                ],
              },
            ],
          },
        ],
      },
      {
        parentCategoryCd: 'EXT',
        parentCategoryDesc: 'Exterior',
        subCategories: [
          {
            l2CatgCd: 'BSM',
            l2CatgName: 'Body Side Moulding',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M66R01-050',
                partDesc: 'BSM Pearl Arctic White',
                catg3DId: 'hp_BodySideMolding',
                'ccOverlappingCodes ': null,
                ccPartTagName: 'BODYSIDEMOULDING',
                ccPartMeshName: 'IGNIS_MMC_ALPHA_ZETA_DELTA_SIGMA_EX_ACC_BSM_PEARL_ARCTIC_WHITE_MESH',
                ccPart3dId: 'IGNIS_MMC_ALPHA_ZETA_DELTA_SIGMA_EX_ACC_BSM_PEARL_ARCTIC_WHITE_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-bsmpearlarcticwhite.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-bsmpearlarcticwhite.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-bsmpearlarcticwhite.jpg',
                ],
              },
              {
                partNum: '990J0M66R01-090',
                partDesc: 'BSM Uptown Red',
                catg3DId: 'hp_BodySideMolding',
                'ccOverlappingCodes ': null,
                ccPartTagName: 'BODYSIDEMOULDING',
                ccPartMeshName: 'IGNIS_MMC_ALPHA_ZETA_DELTA_SIGMA_EX_ACC_BSM_RED_MESH',
                ccPart3dId: 'IGNIS_MMC_ALPHA_ZETA_DELTA_SIGMA_EX_ACC_BSM_RED_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 2944.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-bsmuptownred.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-bsmuptownred.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-bsmuptownred.jpg',
                ],
              },
            ],
          },
          {
            l2CatgCd: 'SPL',
            l2CatgName: 'Spoilers',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M66R07-540',
                partDesc: 'Spoiler & Wheel Arch Kit',
                catg3DId: 'hp_wheelarchkit',
                'ccOverlappingCodes ': [
                  'hp_glasslinespoiler',
                ],
                ccPartTagName: 'WHEEL_ARCH_KIT',
                ccPartMeshName: 'IGNIS_MMC_SIGMA_EX_ACC_WHEELARCH_SPOILER_KIT_MESH',
                ccPart3dId: 'IGNIS_MMC_SIGMA_EX_ACC_WHEELARCH_SPOILER_KIT_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 5790.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-spoiler-wheelarchkit.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-spoiler-wheelarchkit.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-spoiler-wheelarchkit.jpg',
                ],
              },
              {
                partNum: '990J0M66R07-090',
                partDesc: 'Rear mid Glasslione Spoiler Chrome',
                catg3DId: 'hp_glasslinespoiler',
                'ccOverlappingCodes ': [
                  'hp_wheelarchkit',
                ],
                ccPartTagName: 'GLASSLINE_SPOILER',
                ccPartMeshName: 'IGNIS_MMC_DELTA_SIGMA_EX_ACC_GLASSLINE_SPOILER_MESH',
                ccPart3dId: 'IGNIS_MMC_DELTA_SIGMA_EX_ACC_GLASSLINE_SPOILER_MESH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 5690.0,
                qty: 1.0,
                ccThumbnailUrl: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/276x207/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/96x96/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/mobile/72x54/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/324x243/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/263x198/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/96x96/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/thumbnail/desktop/72x54/ignis-rearmidglasslionespoilerchrome.jpg',
                ],
                ccImageUrls: [
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/276x207/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/96x96/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/mobile/72x54/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/324x243/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/263x198/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/96x96/ignis-rearmidglasslionespoilerchrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/ignis/desktop/72x54/ignis-rearmidglasslionespoilerchrome.jpg',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};

const gvAccessories = {
  error: false,
  errors: null,
  data: {
    parentCategories: [
      {
        parentCategoryCd: 'INT',
        parentCategoryDesc: 'Interior',
        subCategories: [
          {
            l2CatgCd: 'MATS',
            l2CatgName: 'Mats',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '75901M76T00',
                partDesc: 'Premium Carpet Mat',
                catg3DId: 'CAM_ACC_FLOOR_MAT',
                ccOverlappingCodes: null,
                ccPartTagName: 'ACC_PREMIMUM_MAT_D_S',
                ccPartMeshName: 'ACC_PREMIMUM_MAT_D_S',
                ccPart3dId: 'ACC_PREMIMUM_MAT_D_S',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-premiumcarpetmat.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-premiumcarpetmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-premiumcarpetmat.jpg'],
              },
              {
                partNum: '75901M76TA0',
                partDesc: 'Black Mat',
                catg3DId: 'CAM_ACC_FLOOR_MAT',
                ccOverlappingCodes: null,
                ccPartTagName: 'ACC_BLACK_MAT_COMMON',
                ccPartMeshName: 'ACC_BLACK_MAT_COMMON',
                ccPart3dId: 'ACC_BLACK_MAT_COMMON',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-blackmat.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-blackmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-blackmat.jpg'],
              },
              {
                partNum: '990J0M76TA3-010',
                partDesc: '3D Boot Mat',
                catg3DId: 'CAM_ACC_3D_BOOT_MAT',
                ccOverlappingCodes: null,
                ccPartTagName: 'S_D_Z_A_ACC_3D_BOOT_MAT',
                ccPartMeshName: 'S_D_Z_A_ACC_3D_BOOT_MAT',
                ccPart3dId: 'S_D_Z_A_ACC_3D_BOOT_MAT',
                isPackage: null,
                packagePriorityOrder: null,
                price: 2944.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-3dbootmat.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-3dbootmat.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-3dbootmat.jpg'],
              },
            ],
          },
          {
            l2CatgCd: 'SCR',
            l2CatgName: 'Seat Covers',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M76TS3-020',
                partDesc: 'Bevel Copper Lining Finish',
                catg3DId: 'hp_in_SeatCover',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_SEATS',
                ccPartMeshName: 'GRAND_VITARA_ALPHA_IN_ACC_SEAT_BEVEL_COPPER_LINING_FINISH',
                ccPart3dId: 'GRAND_VITARA_ALPHA_IN_ACC_SEAT_BEVEL_COPPER_LINING_FINISH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 3793.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-bevelcopperliningfinish.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-bevelcopperliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-bevelcopperliningfinish.jpg'],
              },
              {
                partNum: '990J0M76TS8-010',
                partDesc: 'Premium Enigmatic Brown Finish',
                catg3DId: 'hp_in_SeatCover',
                ccOverlappingCodes: null,
                ccPartTagName: 'IN_SEATS',
                ccPartMeshName: 'GRAND_VITARA_ALPHA_IN_ACC_SEAT_PREMIUM_ENIGMATIC_BROWN_FINISH',
                ccPart3dId: 'GRAND_VITARA_ALPHA_IN_ACC_SEAT_PREMIUM_ENIGMATIC_BROWN_FINISH',
                isPackage: null,
                packagePriorityOrder: null,
                price: 2944.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-premiumbrownliningfinish.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-premiumbrownliningfinish.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-premiumbrownliningfinish.jpg'],
              },
            ],
          },
          {
            l2CatgCd: 'SHD',
            l2CatgName: 'Sun Shade',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M76TU0-010',
                partDesc: 'Window Sunshade ( 4 Door)',
                catg3DId: 'CAM_ACC_SUNSHADE_4',
                ccOverlappingCodes: ['CAM_ACC_SUNSHADE_2'],
                ccPartTagName: 'COMMON_ACC_IN_WINDOW_SUNSHADE_4_DOOR',
                ccPartMeshName: 'COMMON_ACC_IN_WINDOW_SUNSHADE_4_DOOR',
                ccPart3dId: 'COMMON_ACC_IN_WINDOW_SUNSHADE_4_DOOR',
                isPackage: null,
                packagePriorityOrder: null,
                price: 1673.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-windowsunshade4door.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-windowsunshade4door.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-windowsunshade4door.jpg'],
              },
              {
                partNum: '990J0M76TU0-020',
                partDesc: 'Window Sunshade ( 2 Rear Door)',
                catg3DId: 'CAM_ACC_SUNSHADE_2',
                ccOverlappingCodes: ['CAM_ACC_SUNSHADE_4'],
                ccPartTagName: 'COMMON_ACC_IN_WINDOW_SUNSHADE_2_REAR_DOOR',
                ccPartMeshName: 'COMMON_ACC_IN_WINDOW_SUNSHADE_2_REAR_DOOR',
                ccPart3dId: 'COMMON_ACC_IN_WINDOW_SUNSHADE_2_REAR_DOOR',
                isPackage: null,
                packagePriorityOrder: null,
                price: 944.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-windowsunshade2reardoor.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-windowsunshade2reardoor.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-windowsunshade2reardoor.jpg'],
              },
            ],
          },
          {
            l2CatgCd: 'STI',
            l2CatgName: 'Styling Kit',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M76TPJ-010',
                partDesc: 'Interior Styling Kit - Grey Mystic Marble',
                catg3DId: 'CAM_ACC_STYLING_KIT',
                ccOverlappingCodes: null,
                ccPartTagName: 'COMMON_ACC_IN_STYLING_KIT_GREY_MYSTIC_MARBLE',
                ccPartMeshName: 'COMMON_ACC_IN_STYLING_KIT_GREY_MYSTIC_MARBLE',
                ccPart3dId: null,
                isPackage: null,
                packagePriorityOrder: null,
                price: 1790.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-interiorstylingkit-greymysticmarble.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-interiorstylingkit-greymysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-interiorstylingkit-greymysticmarble.jpg'],
              },
              {
                partNum: '990J0M76TPJ-020',
                partDesc: 'Interior Styling Kit - Copper Mystic Marble',
                catg3DId: 'CAM_ACC_STYLING_KIT',
                ccOverlappingCodes: null,
                ccPartTagName: 'COMMON_ACC_IN_STYLING_KIT_COPPER_MYSTIC_MARBLE',
                ccPartMeshName: 'COMMON_ACC_IN_STYLING_KIT_COPPER_MYSTIC_MARBLE',
                ccPart3dId: null,
                isPackage: null,
                packagePriorityOrder: null,
                price: 1390.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-interiorstylingkit-coppermysticmarble.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-interiorstylingkit-coppermysticmarble.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-interiorstylingkit-coppermysticmarble.jpg'],
              },
            ],
          },
        ],
      },
      {
        parentCategoryCd: 'EXT',
        parentCategoryDesc: 'Exterior',
        subCategories: [

          {
            l2CatgCd: 'SIG',
            l2CatgName: 'Sill Guard',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M76TM8-010',
                partDesc: 'Mystic Metal Door Sill Guard',
                catg3DId: 'CAM_ACC_SILL_GUARD',
                ccOverlappingCodes: null,
                ccPartTagName: 'ACC_MYSTIC_DOOR_SILL_GUARD_COMMON',
                ccPartMeshName: 'ACC_MYSTIC_DOOR_SILL_GUARD_COMMON',
                ccPart3dId: 'ACC_MYSTIC_DOOR_SILL_GUARD_COMMON',
                isPackage: null,
                packagePriorityOrder: null,
                price: 1590.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-mysticmetaldoorsillguard.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-mysticmetaldoorsillguard.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-mysticmetaldoorsillguard.jpg'],
              },
              {
                partNum: '990J0M76TM6-010',
                partDesc: 'Illuminated Door Sill Guard - Luxe Brown',
                catg3DId: 'CAM_ACC_SILL_GUARD',
                ccOverlappingCodes: null,
                ccPartTagName: 'S_D_Z_A_ACC_IN_ILLUMI_DOOR_SILLGUARD_LUXE_BROWN',
                ccPartMeshName: 'S_D_Z_A_ACC_IN_ILLUMI_DOOR_SILLGUARD_LUXE_BROWN',
                ccPart3dId: 'S_D_Z_A_ACC_IN_ILLUMI_DOOR_SILLGUARD_LUXE_BROWN',
                isPackage: null,
                packagePriorityOrder: null,
                price: 1190.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-illuminateddoorsillguard-luxebrown.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-illuminateddoorsillguard-luxebrown.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-illuminateddoorsillguard-luxebrown.jpg'],
              },
            ],
          },
          {
            l2CatgCd: 'FRB',
            l2CatgName: 'Front Bumper',
            ccCatgSortOrder: null,
            accessories: [
              {
                partNum: '990J0M76T07-010',
                partDesc: 'Front Bumper Garnish - Chrome',
                catg3DId: 'CAM_ACC_FRONT_BUMPER',
                ccOverlappingCodes: null,
                ccPartTagName: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_CHROME',
                ccPartMeshName: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_CHROME',
                ccPart3dId: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_CHROME',
                isPackage: null,
                packagePriorityOrder: null,
                price: 1790.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-frontbumpergarnish-chrome.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-frontbumpergarnish-chrome.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-frontbumpergarnish-chrome.jpg'],
              },
              {
                partNum: '990J0M76T07-020',
                partDesc: 'Front Bumper Garnish - Smoked',
                catg3DId: 'CAM_ACC_FRONT_BUMPER',
                ccOverlappingCodes: null,
                ccPartTagName: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_SMOKED',
                ccPartMeshName: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_SMOKED',
                ccPart3dId: 'COMMON_ACC_EX_FRONT_BUMPER_GARNISH_SMOKED',
                isPackage: null,
                packagePriorityOrder: null,
                price: 1590.0,
                qty: 1.0,
                ccThumbnailUrl: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/276x207/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/96x96/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/mobile/72x54/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/324x243/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/263x198/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/96x96/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/thumbnail/desktop/72x54/grandvitara-frontbumpergarnish-smoked.jpg'],
                ccImageUrls: ['/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/276x207/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/96x96/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/mobile/72x54/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/324x243/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/263x198/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/96x96/grandvitara-frontbumpergarnish-smoked.jpg',
                  '/content/dam/msil/nexa/in/en/assets/car-configurator/images/cars/grand-vitara/desktop/72x54/grandvitara-frontbumpergarnish-smoked.jpg'],
              },
            ],
          },
        ],
      },
    ],
  },
};

const stubbedResponse = {
  ignisAccessories,
  gvAccessories,
};

export { stubbedResponse };
