name: Update commons in Repository nexa

on:
  repository_dispatch:
    types: [commons-updated]

jobs:
  update-commons:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository Anexa
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for the repository

      # Step 2: Set up Git configuration
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Remove the existing commons1 folder from Git's index (if it exists)
      - name: Remove existing commons from Git index
        run: |
          if [ -d "commons" ]; then
            git rm -r --cached commons
            git commit -m "Remove existing commons folder from Git index"
          fi

      # Step 4: Clone or update the commons repository into the commons folder
      - name: Update commons folder
        run: |
          rm -rf commons
          git submodule add https://github.com/samgec123/submodule-commons.git commons
          git submodule update --init --recursive
          git commit -m "Added commons as a submodule"
          git push origin main
